apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  image: {{ image }}
  schedule: "{{ schedule }}"
  ttlSecondsAfterFinished: 340
  backoffLimit: 2
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 800m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: {{ application.eux-journalarkivar.name }}
  azure:
    application:
      enabled: true
  env:
    - name: CLIENT_EUXJOURNALARKIVAR_ENDPOINT
      value: {{ application.eux-journalarkivar.endpoint }}
    - name: CLIENT_EUXJOURNALARKIVAR_SCOPE
      value: {{ application.eux-journalarkivar.scope }}
