name: eux-journalarkivar-naisjob
schedule: '0 1 * * *'

application:
  eux-journalarkivar:
    name: eux-journalarkivar
    namespace: eessibasis
    endpoint: http://eux-journalarkivar
    scope: api://prod-gcp.eessibasis.eux-journalarkivar/.default

cluster:
  fss: prod-fss
  gcp: prod-gcp
