name: eux-journalarkivar-ferdigstill-naisjob
schedule: "50 12 * * *"

arkivarprosess: ferdigstill

application:
  eux-journalarkivar:
    name: eux-journalarkivar
    namespace: eessibasis
    endpoint: http://eux-journalarkivar
    scope: api://prod-gcp.eessibasis.eux-journalarkivar/.default
