name: eux-journalarkivar-feilregistrer-naisjob
schedule: "0 2 * * *"

arkivarprosess: feilregistrer

application:
  eux-journalarkivar:
    name: eux-journalarkivar
    namespace: eessibasis
    endpoint: http://eux-journalarkivar
    scope: api://prod-gcp.eessibasis.eux-journalarkivar/.default
