name: eux-journalarkivar-feilregistrer-naisjob
schedule: "0 1 * * *"

arkivarprosess: feilregistrer

application:
  eux-journalarkivar:
    name: eux-journalarkivar
    namespace: eessibasis
    endpoint: http://eux-journalarkivar
    scope: api://dev-gcp.eessibasis.eux-journalarkivar/.default

cluster:
  fss: dev-fss
  gcp: dev-gcp
